//
//  MWCDescriptorFetchResult.m
//  MyControlWidget
//
//  Created by Jinwoo Kim on 9/14/24.
//

#import "MWCDescriptorFetchResult.h"

/*
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
     <key>$archiver</key>
     <string>NSKeyedArchiver</string>
     <key>$objects</key>
     <array>
         <string>$null</string>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>16</integer>
             </dict>
             <key>NS.objects</key>
             <array>
                 <dict>
                     <key>CF$UID</key>
                     <integer>2</integer>
                 </dict>
             </array>
         </dict>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>15</integer>
             </dict>
             <key>backgroundRemovable</key>
             <true/>
             <key>backgroundStyle</key>
             <integer>0</integer>
             <key>defaultIntent2</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>displayName</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>6</integer>
             </dict>
             <key>enablement</key>
             <integer>0</integer>
             <key>enablesMultipleTapTargets</key>
             <false/>
             <key>eventMachServiceName</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>extensionIdentity</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>3</integer>
             </dict>
             <key>hiddenBySensitiveUI</key>
             <false/>
             <key>intentRecommendationsContainer</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>intentType</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>kind</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>12</integer>
             </dict>
             <key>localeToken</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>8</integer>
             </dict>
             <key>nativeCBI</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>platform</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>10</integer>
             </dict>
             <key>promptsForUserConfiguration</key>
             <false/>
             <key>sdkVersion</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>9</integer>
             </dict>
             <key>supportedSizeClasses</key>
             <integer>14</integer>
             <key>supportsAccentedContent</key>
             <true/>
             <key>supportsInteraction</key>
             <true/>
             <key>supportsVibrantContent</key>
             <false/>
             <key>unsupLoca</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>13</integer>
             </dict>
             <key>version</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>11</integer>
             </dict>
             <key>widgetDescription</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>7</integer>
             </dict>
             <key>widgetVisibility</key>
             <integer>0</integer>
         </dict>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>5</integer>
             </dict>
             <key>containerBundleIdentifier</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>deviceIdentifier</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>extensionBundleIdentifier</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>4</integer>
             </dict>
         </dict>
         <string>com.pookjw.MyApp2.ControlWidget</string>
         <dict>
             <key>$classes</key>
             <array>
                 <string>CHSExtensionIdentity</string>
                 <string>NSObject</string>
             </array>
             <key>$classname</key>
             <string>CHSExtensionIdentity</string>
         </dict>
         <string>My Widget</string>
         <string>This is an example widget.</string>
         <data>
         5wnQ1lqY4jVXYCRH1BnUm+V5Uf0=
         </data>
         <string>18.1</string>
         <integer>3</integer>
         <integer>1</integer>
         <string>ControlWidget</string>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>14</integer>
             </dict>
             <key>NS.keys</key>
             <array/>
             <key>NS.objects</key>
             <array/>
         </dict>
         <dict>
             <key>$classes</key>
             <array>
                 <string>NSDictionary</string>
                 <string>NSObject</string>
             </array>
             <key>$classname</key>
             <string>NSDictionary</string>
         </dict>
         <dict>
             <key>$classes</key>
             <array>
                 <string>CHSWidgetDescriptor</string>
                 <string>CHSBaseDescriptor</string>
                 <string>NSObject</string>
             </array>
             <key>$classname</key>
             <string>CHSWidgetDescriptor</string>
         </dict>
         <dict>
             <key>$classes</key>
             <array>
                 <string>NSArray</string>
                 <string>NSObject</string>
             </array>
             <key>$classname</key>
             <string>NSArray</string>
         </dict>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>16</integer>
             </dict>
             <key>NS.objects</key>
             <array>
                 <dict>
                     <key>CF$UID</key>
                     <integer>18</integer>
                 </dict>
             </array>
         </dict>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>27</integer>
             </dict>
             <key>actionMetadata</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>24</integer>
             </dict>
             <key>backgroundStyle</key>
             <integer>0</integer>
             <key>controlVersion</key>
             <integer>1</integer>
             <key>defaultIntentRef</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>disablesControlStateCaching</key>
             <false/>
             <key>displayName</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>20</integer>
             </dict>
             <key>enablement</key>
             <integer>0</integer>
             <key>eventMachServiceName</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>extensionIdentity</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>19</integer>
             </dict>
             <key>hiddenBySensitiveUI</key>
             <false/>
             <key>hiddenControl</key>
             <true/>
             <key>intentType</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>kind</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>23</integer>
             </dict>
             <key>localeToken</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>22</integer>
             </dict>
             <key>nativeCBI</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>platform</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>10</integer>
             </dict>
             <key>promptsForUserConfiguration</key>
             <false/>
             <key>sdkVersion</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>9</integer>
             </dict>
             <key>showContextualMenu</key>
             <false/>
             <key>size</key>
             <integer>0</integer>
             <key>supportsPush</key>
             <false/>
             <key>supportsVibrantContent</key>
             <false/>
             <key>type</key>
             <integer>1</integer>
             <key>version</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>11</integer>
             </dict>
             <key>widgetDescription</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>21</integer>
             </dict>
             <key>widgetVisibility</key>
             <integer>0</integer>
         </dict>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>5</integer>
             </dict>
             <key>containerBundleIdentifier</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>deviceIdentifier</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>0</integer>
             </dict>
             <key>extensionBundleIdentifier</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>4</integer>
             </dict>
         </dict>
         <string>Timer</string>
         <string>A an example control that runs a timer.</string>
         <data>
         5wnQ1lqY4jVXYCRH1BnUm+V5Uf0=
         </data>
         <string>com.pookjw.MyApp2.ControlWidget</string>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>26</integer>
             </dict>
             <key>intentType</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>25</integer>
             </dict>
             <key>isCameraCapture</key>
             <false/>
             <key>isLauncher</key>
             <false/>
         </dict>
         <string>appintent:StartTimerIntent</string>
         <dict>
             <key>$classes</key>
             <array>
                 <string>CHSControlActionMetadata</string>
                 <string>NSObject</string>
             </array>
             <key>$classname</key>
             <string>CHSControlActionMetadata</string>
         </dict>
         <dict>
             <key>$classes</key>
             <array>
                 <string>CHSControlDescriptor</string>
                 <string>CHSBaseDescriptor</string>
                 <string>NSObject</string>
             </array>
             <key>$classname</key>
             <string>CHSControlDescriptor</string>
         </dict>
         <dict>
             <key>$class</key>
             <dict>
                 <key>CF$UID</key>
                 <integer>16</integer>
             </dict>
             <key>NS.objects</key>
             <array/>
         </dict>
     </array>
     <key>$top</key>
     <dict>
         <key>activityDescriptors</key>
         <dict>
             <key>CF$UID</key>
             <integer>28</integer>
         </dict>
         <key>controlDescriptors</key>
         <dict>
             <key>CF$UID</key>
             <integer>17</integer>
         </dict>
         <key>widgetDescriptors</key>
         <dict>
             <key>CF$UID</key>
             <integer>1</integer>
         </dict>
     </dict>
     <key>$version</key>
     <integer>100000</integer>
 </dict>
 </plist>
 */

@implementation MWCDescriptorFetchResult

+ (BOOL)supportsSecureCoding {
    return YES;
}

- (instancetype)initWithCoder:(NSCoder *)coder {
    abort();
}

- (void)dealloc {
    [_activityDescriptors release];
    [_controlDescriptors release];
    [_widgetDescriptors release];
    [super dealloc];
}

- (void)encodeWithCoder:(NSCoder *)coder {
    [coder encodeObject:nil forKey:@"activityDescriptors"]; // CHSMutableWidgetDescriptor (CHSWidgetDescriptor)
    [coder encodeObject:nil forKey:@"controlDescriptors"]; // CHSMutableControlDescriptor (CHSControlDescriptor)
    [coder encodeObject:nil forKey:@"widgetDescriptors"]; // CHSMutableWidgetDescriptor (CHSWidgetDescriptor)
}

@end
